test: I from gitHub weather app

server:
  port: 8060
  context-path: /weatherapp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
mybatis:
  type-aliases-package: com.china.group.vo
  mapper-locations: classpath:mapper/*.xml
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
